version: "3.7"
services:

  backend:
    container_name: audio_backend
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      HOST_DB: db
      PORT_DB: 5432
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: audio_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "audio"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - app_network

  minio:
    container_name: audio_minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  app_network:
    driver: bridge
volumes:
  postgres_data:
  minio-storage: